dist: bionic

sudo: false

git:
  quiet: true

branches:
  only:
    - master

addons:
  apt:
    update: true
    packages:
      - doxygen
      - libeigen3-dev

script: >-
  doxygen Doxyfile &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
