dist: xenial

sudo: false

git:
  quiet: true

branches:
  only:
    - master

addons:
  apt:
    update: true
    packages:
      - doxygen
      - qt5-default
      - libeigen3-dev

script: >-
  qmake example/bezier_example.pro &&
  make &&
  doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
